version: '3'
services:

  server:
    image: kryptopolis/backend
    env_file: .env
    container_name: kryptopolis_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
#    command: bash -c "npm run dev"
    links:
      - mongo
    volumes:
      - .:/app

  mongo:
    ports:
      - "27017:27017"
    image: mongo:3.5.13
    volumes:
      - ./etc/mongo:/data/db

