import "../../support/hook"

const url = '/v1/feed'

describe(__filename, () => {
  let feed
  let response = `
    <?xml version="1.0" encoding="utf-8"?>
    <rss version="2.0">
      <channel>
        <title>RSS Stream Feed</title>
        <link>https://feedity.com/</link>
        <description>RSS Stream Feed (Generated by Feedity)</description>
      </channel>
    </rss>
  `
  const responseJson = {
    items: [],
    title: 'RSS Stream Feed',
    description: 'RSS Stream Feed (Generated by Feedity)',
    url: 'https://feedity.com/',
    image: ''
  }

  beforeEach(() => {
    feed = nock(/feedity.com/).get(/[\w\:\/\.]+/).reply(200, response)
  })

  afterEach(() => {
    nock.cleanAll()
  })

  it("should return valid attributes", async () => {
    let res = await request(url, { unauth: true })

    expect(feed.isDone()).to.be.true
    expect(res.body).to.eql(responseJson)
  })

})
